spring:
  application:
    name: my-spboot-web-app
  datasource:
    url: jdbc:postgresql://localhost:5432/springweb
    username: principal_dba
    password: thedba
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      
server:
  port: '3000'
  
logging:
  level:
    root: WARN
  file:
    name: my-spboot-web-app.log
    max-size: 10MB
    max-history: '10'
